### ISSUE TITLE
Etsy store links dead

### ISSUE THREAD

**Issue by AGSPhoenix** [tanvach/prettygood_dsp#1]
The various links to your store in this repo and on your site are dead, with no useful explanation from them as to why. Are you still selling these kits?

If not, any plans to release the STLs and Gerbers so we can make our own?

**Comment by tanvach** [comment]
Hello - we're closing our store and will release the files sometime this month.

**Comment by tanvach** [comment]
Updated to remove the Etsy store link. Added PCB files (gerber + easyeda json), case 3d model files, and programmer files.
